GET http://localhost:3001/todos

###
POST http://localhost:3001/todo/new
Content-Type: application/json

{
  "text": "Dance"
}   


###
DELETE  http://localhost:3001/todo/delete/63f7ca1b7f82d5621e7954ef


###
PUT http://localhost:3001/todo/complete/63f7ca127f82d5621e7954ed